uPD8255 GPIO
GLGPrograms/ceda-rom-disassembly pull request #11
Opened 2023-02-24 12:21 UTC by giomba

This MR introduces documentation for uPD8255 (GPIO) IC.
Or at least, that's what I think it is at IO address $80-$83.

:warning: This is just intuition. Before merging, tests must be conducted on the real hardware.

2023-02-27 20:32 UTC, giomba commented
I reviewed this a bit, via direct inspection on the board, with @giuliof . Even if incomplete, I'll change this MR's status as "ready" (as always, to avoid clogging the queue and having rebase-induced headaches)

2023-03-01 20:05 UTC, giuliof requested changes

2023-03-01 20:05 UTC, giuliof commented on V1.01_ROM_disassembly_C000.asm
> +    jr      nz,label_c216                   ;[c227]
This change conflicts with FDC branch. Since is only one line comment, I suggest to revert-and-squash to avoid merging issues

2023-03-01 20:05 UTC, giuliof commented on V1.01_ROM_disassembly_C000.asm
> +    jr      nz,label_c26c                   ;[c27d]
same as before

2023-03-01 20:05 UTC, giuliof commented on V1.01_ROM_disassembly_C000.asm
> +    jr      nz,label_c32a                   ;[c338]
same as before

2023-03-01 20:05 UTC, giuliof commented on V1.01_ROM_disassembly_C000.asm
same as before

2023-03-01 21:20 UTC, giuliof approved these changes

2023-03-01 21:20 UTC, merged